### ISSUE TITLE
SSLException: Unrecognized SSL message, plaintext connect

### ISSUE THREAD

**Issue by ghost** [escline/InstallCert#10]
Hi.
I think this is more a question than an issue.
Thing is, I'm trying to use InstallCert to resolve a problem I'm having with another extension (https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/81)
but I keep getting this error:
![image](https://user-images.githubusercontent.com/23528701/39588083-69b1f698-4ed1-11e8-805c-098d6a4988c3.png)
(I just changed the IP for security reasons). I have looked the other issues but did not find a similar one.

Searching for it on google, it states that this error happened when trying to accesss HTTPS urls. 
Is there any way that this is related to this situation?
And how can I fix it?
Thank you

Edit:
Just did a test with Google and it worked fine:
![image](https://user-images.githubusercontent.com/23528701/39588311-ef16bbf2-4ed1-11e8-8f73-ff707fac669e.png)

How could I get this to work with my server? The IP XX.X.X.XXX:443 did not work, because we have a specific port

**Comment by muzikurry** [comment]
I have got the same issue. 

D:\>java InstallCert localhost:8090
Loading KeyStore D:\Java\lib\security\cacerts...
Opening connection to localhost:8090...
Starting SSL handshake...

javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at InstallCert.main(InstallCert.java:98)
Could not obtain server certificate chain

**Comment by escline** [comment]
The host and port you are connecting to must be an SSL connection. If it's not, you will get the "javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?" message.

https://stackoverflow.com/questions/6532273/unrecognized-ssl-message-plaintext-connection-exception
