### ISSUE TITLE
Command line help should indicate that hostname is required

### ISSUE THREAD

**Issue by cowwoc** [escline/InstallCert#3]
https://github.com/escline/InstallCert/blob/master/InstallCert.java#L64 returns:

```
Usage: java InstallCert [:port] [passphrase]
```

notice how `hostname` is missing. Please update this line to:

```
Usage: java InstallCert <host>[:port] [passphrase]
```

or something along those lines, indicating that the hostname is required.

**Comment by escline** [comment]
Fixed! Thanks
