### ISSUE TITLE
Allow to configure system proxy, so the tools works when behind a proxy too.

### ISSUE THREAD

**Issue by victorpablosceruelo** [escline/InstallCert#9]
I made some modifications to be able to configure proxy in command line. 
java -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3128 InstallCert dl.google.com:443

Please allow me to commit changes. Copy of new code attached.

[InstallCert.zip](https://github.com/escline/InstallCert/files/1165103/InstallCert.zip)

**Comment by brenosilver** [comment]
Any way to set proxy credentials with this? We are behind a proxy that requires authentication and this solution does not work in this instance. I'm trying to figure it out for a while now without much success.

**Comment by iksnalybok** [comment]
PR https://github.com/escline/InstallCert/pull/11 does more or less the same (but requires explicit option rather than using env/sys variables).
For authentication, using a local proxy like http://cntlm.sourceforge.net/ can help.

**Comment by escline** [comment]
Merged PR #11 so proxy is now supported. Thanks @iksnalybok 👍
